# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Hosting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: egordm/gha-yarn-node-cache@v1

    - name: Install JS dependencies
      run: yarn install
      
    - name: Build
      run: yarn build
      
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.1.5 
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "public/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
  
    - name: Slack Notification
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: FulanBot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
